//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinezAI.WPFApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedUserName {
            get {
                return ((string)(this["SavedUserName"]));
            }
            set {
                this["SavedUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sk-proj-6y5Avz9uc0HaCtUm9a17WJdI51477y-0UuahswxhHyA0rjrQJJojM9R1vv4619py6r6mCzwyt" +
            "-T3BlbkFJW-ypm1wcyXUQNL-5E4I5VebLSVj-IaWGDWurbnLNGzZoJdZ0aiXPcyfoIkwDQwyayJdmhx2" +
            "sgA")]
        public string OpenAIKey {
            get {
                return ((string)(this["OpenAIKey"]));
            }
            set {
                this["OpenAIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int MaxTMP {
            get {
                return ((int)(this["MaxTMP"]));
            }
            set {
                this["MaxTMP"] = value;
            }
        }
    }
}
